export const SetCodes: Record<string,string> = {
    //SV
    'PAL': 'SV02',
    'SVI': 'SV01',
    'PR-SV': 'SV',
    //SWSH
    'CRZ-GG': 'CRZ:GG',
    'CRZ': 'CRZ',
    'SIT-TG': 'SWSH12: TG',
    'SIT': 'SWSH12',
    'LOR-TG': 'SWSH11: TG',
    'LOR': 'SWSH11',
    'PGO': 'PGO',
    'ASR-TG': 'SWSH10:TG',
    'ASR': 'SWSH10',
    'BRS-TG': 'SWSH09:TG',
    'BRS': 'SWSH09',
    'FST': 'SWSH08',
    'EVS': 'SWSH07',
    'CRE': 'SWSH06',
    'BST': 'SWSH05',
    'CEL': 'CLB',    
    'SHF': 'SHF',
    'VIV': 'SWSH04',
    'CPA': 'CHP',
    'DAA': 'SWSH03',
    'RCL': 'SWSH02',
    'SSH': 'SWSH01',
    'PR-SW':'SWSD',
}

export const SetCodesSearch: Record<string,string> = {
    //SV
    'PAL': 'SV02',
    'SVI': 'SV01',
    'PR-SV': 'Promo',
    //SWSH
    'CRZ-GG': 'Crown Zenith',
    'CRZ': 'Crown Zenith',
    'SIT-TG': 'SWSH12',
    'SIT': 'SWSH12',
    'LOR-TG': 'SWSH11',
    'LOR': 'SWSH11',
    'PGO': 'Pokemon Go',
    'ASR-TG': 'SWSH10',
    'ASR': 'SWSH10',
    'BRS-TG': 'SWSH09',
    'BRS': 'SWSH09',
    'FST': 'SWSH08',
    'CEL': 'Celebrations',
    'EVS': 'SWSH07',
    'CRE': 'SWSH06',
    'BST': 'SWSH05',
    'SHF': 'Shining Fates',
    'VIV': 'SWSH04',
    'CPA': 'Champion\'s Path',
    'DAA': 'SWSH03',
    'RCL': 'SWSH02',
    'SSH': 'SWSH01',
    'PR-SW':'Promo',
}
