export const SetCodes: Record<string,string> = {
    'SVI': 'SV01',
    'PR-SW':'SWSD',
    'CRZ-GG': 'CRZ:GG',
    'CRZ': 'CRZ',
    'SIT-TG': 'SWSH12: TG',
    'SIT': 'SWSH12',
    'LOR-TG': 'SWSH11: TG',
    'LOR': 'SWSH11',
    'ASR-TG': 'SWSH10:TG',
    'ASR': 'SWSH10',
    'BRS-TG': 'SWSH09:TG',
    'BRS': 'SWSH09',
    'FST': 'SWSH08',
    'EVS': 'SWSH07',
    'CRE': 'SWSH06',
    'BST': 'SWSH05',
    'CEL': 'CLB',
}

export const SetCodesSearch: Record<string,string> = {
    'SVI': 'SV01',
    'PR-SW':'Promo',
    'CRZ-GG': 'Crown Zenith',
    'CRZ': 'Crown Zenith',
    'SIT-TG': 'SWSH12',
    'SIT': 'SWSH12',
    'LOR-TG': 'SWSH11',
    'LOR': 'SWSH11',
    'ASR-TG': 'SWSH10',
    'ASR': 'SWSH10',
    'BRS-TG': 'SWSH09',
    'BRS': 'SWSH09',
    'FST': 'SWSH08',
    'EVS': 'SWSH07',
    'CRE': 'SWSH06',
    'BST': 'SWSH05',
    'CEL': 'Celebrations',
}
